### PR TITLE
Update eslint to ^5.16.0, drop babel-eslint

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by papandreou** [comment]
Seems like we'll have to drop node.js 4 and 5 support for this to work, as eslint no longer supports them. I guess that makes this suggested change semver-major.

**Comment by papandreou** [comment]
Ping @zertosh? Would be really nice to move forward with this and https://github.com/zertosh/eslint-plugin-no-async-without-await/pull/2 :)

**Comment by zertosh** [comment]
@papandreou, if you're using a newer ESLint, why aren't you using this: https://eslint.org/docs/rules/require-await

**Comment by papandreou** [comment]
@zertosh, oh, I did not know that existed -- thanks, will switch to that!

Feel free to just close my PRs if you think its better to abandon this plugin. Might be good to point people at `require-await` in that case.

**Comment by zertosh** [comment]
This project is now deprecated. See zertosh/eslint-plugin-no-async-without-await#4.

**Pull request closed without merging**
